"""Build ArtworkAgent.exe (one-file) with ONLY the Chromium browser bundled.

Keeps the download small by:
  - bundling only the chromium-<ver> folder Playwright actually uses (no
    Firefox, WebKit, headless_shell, or ffmpeg),
  - excluding server-only and unused heavy modules (fastapi/uvicorn/starlette/
    httpx/scipy/imagehash and common accidental sweeps).

cv2 (OpenCV) is NOT excluded: the agent runs the aspect-ratio workflow, which
calls similarity()/extract_features() in src/postprocess.py — those use cv2.

Run inside the activated venv:  python build_agent.py
"""
from __future__ import annotations

import os
import re
import subprocess
import sys
from pathlib import Path


def chromium_folder() -> Path:
    """Resolve the exact chromium-<ver> folder the installed Playwright uses."""
    from playwright.sync_api import sync_playwright
    pw = sync_playwright().start()
    try:
        exe = pw.chromium.executable_path
    finally:
        pw.stop()
    # .../ms-playwright/chromium-1234/chrome-win64/chrome.exe -> chromium-1234 dir
    p = Path(exe)
    for parent in p.parents:
        if re.match(r"chromium-\d+$", parent.name):
            return parent
    raise RuntimeError(f"Could not locate chromium-<ver> folder from {exe}")


EXCLUDES = [
    # OpenCV — server-side only (src/compare.py). The agent produces images;
    # the aspect-ratio comparison/shape analysis runs on the server. Its large
    # .pyd is also what broke PyInstaller one-file extraction.
    "cv2",
    # Server-only web stack — never used by the agent.
    "fastapi", "uvicorn", "starlette", "httpx", "httpcore", "h11",
    # phash is now numpy-only; these are no longer needed and are large.
    "scipy", "imagehash",
    # Common accidental heavyweight sweeps.
    "matplotlib", "PyQt5", "PyQt6", "PySide2", "PySide6",
    "pandas", "notebook", "IPython", "tkinter.test", "test",
]

_SPEC_TEMPLATE = '''# Auto-generated by build_agent.py — do not edit by hand.
# Bundles ONLY the resolved Chromium folder (no Firefox/WebKit/headless_shell)
# and excludes server-only + unused heavy modules. The browser tree is added
# via Analysis(datas=...) with a recursive Tree so chrome.exe and every nested
# binary are preserved (a plain --add-data drops chrome.exe).
import os
from PyInstaller.utils.hooks import collect_all

CHROME_DIR = r"{chrome_dir}"
CHROME_PREFIX = "ms-playwright/{chrome_name}"

# Playwright package data/binaries/hidden imports (2-tuples for datas param).
pw_datas, pw_binaries, pw_hidden = collect_all("playwright")

# Recursively enumerate the Chromium folder as (source, dest_dir) 2-tuples so
# the Analysis normaliser turns them into proper 3-tuple DATA entries.
chrome_datas = []
for _r, _d, _files in os.walk(CHROME_DIR):
    for _f in _files:
        _src = os.path.join(_r, _f)
        _reldir = os.path.relpath(_r, CHROME_DIR)
        _dest = CHROME_PREFIX if _reldir == "." else os.path.join(CHROME_PREFIX, _reldir)
        chrome_datas.append((_src, _dest))

a = Analysis(
    ["agent_gui.py"],
    pathex=[r"{root}"],
    binaries=pw_binaries,
    datas=[("src", "src"), ("config", "config")] + pw_datas + chrome_datas,
    hiddenimports=["pystray._win32", "PIL.Image", "PIL.ImageDraw"] + pw_hidden,
    hookspath=[],
    runtime_hooks=["pyi_rth_playwright.py"],
    excludes={excludes},
    noarchive=False,
)
pyz = PYZ(a.pure)
# ONE-DIR build: the bootloader loads files from the app folder directly, so
# there is NO runtime extraction step — this avoids the "decompression return
# code -1" failure that one-file hits on large files (chrome.dll, cv2.pyd).
exe = EXE(
    pyz, a.scripts, [],
    exclude_binaries=True,
    name="ArtworkAgent",
    debug=False, bootloader_ignore_signals=False, strip=False,
    upx=False, console={console}, disable_windowed_traceback=False,
)
coll = COLLECT(
    exe, a.binaries, a.datas,
    strip=False, upx=False, name="ArtworkAgent",
)
'''


def main() -> None:
    root = Path(__file__).parent
    chrome_dir = chromium_folder()
    print(f"[build] bundling only: {chrome_dir.name}  ({chrome_dir})")

    spec_path = root / "ArtworkAgent.spec"
    console = os.getenv("AGENT_BUILD_CONSOLE") == "1"
    spec_path.write_text(_SPEC_TEMPLATE.format(
        chrome_dir=str(chrome_dir), chrome_name=chrome_dir.name,
        root=str(root), excludes=repr(EXCLUDES), console=str(console),
    ), encoding="utf-8")

    print("[build] running PyInstaller from generated spec…")
    subprocess.check_call(
        [sys.executable, "-m", "PyInstaller", "--noconfirm", "--clean", str(spec_path)],
        cwd=str(root),
    )

    app_dir = root / "dist" / "ArtworkAgent"
    exe = app_dir / "ArtworkAgent.exe"
    if not exe.exists():
        print("[build] FAILED — dist/ArtworkAgent/ArtworkAgent.exe not found.")
        sys.exit(1)

    # Folder size (what the designer unzips to).
    folder_bytes = sum(f.stat().st_size for f in app_dir.rglob("*") if f.is_file())

    # Zip the one-dir app for distribution.
    import shutil
    zip_base = root / "dist" / "ArtworkAgent"
    print("[build] zipping the app folder for distribution…")
    zip_path = Path(shutil.make_archive(str(zip_base), "zip", root_dir=str(root / "dist"), base_dir="ArtworkAgent"))
    zip_bytes = zip_path.stat().st_size

    print()
    print(f"[build] DONE (one-dir): {app_dir}")
    print(f"[build] unpacked folder: {folder_bytes:,} bytes  (~{folder_bytes/(1024*1024):.0f} MB)")
    print(f"[build] download ZIP:    {zip_path}")
    print(f"[build] zip size:        {zip_bytes:,} bytes  (~{zip_bytes/(1024*1024):.0f} MB)")
    print("[build] copy dist/ArtworkAgent.zip into the server's downloads/ folder to publish it.")


if __name__ == "__main__":
    main()
