"""Build ArtworkAgent.exe (one-file) with ONLY the Chromium browser bundled.

Keeps the download small by:
  - bundling only the chromium-<ver> folder Playwright actually uses (no
    Firefox, WebKit, headless_shell, or ffmpeg),
  - excluding server-only and unused heavy modules (fastapi/uvicorn/starlette/
    httpx/scipy/imagehash and common accidental sweeps).

cv2 (OpenCV) is NOT excluded: the agent runs the aspect-ratio workflow, which
calls similarity()/extract_features() in src/postprocess.py — those use cv2.

Run inside the activated venv:  python build_agent.py
"""
from __future__ import annotations

import os
import re
import subprocess
import sys
from pathlib import Path


def chromium_folder() -> Path:
    """Resolve the exact chromium-<ver> folder the installed Playwright uses."""
    from playwright.sync_api import sync_playwright
    pw = sync_playwright().start()
    try:
        exe = pw.chromium.executable_path
    finally:
        pw.stop()
    # .../ms-playwright/chromium-1234/chrome-win64/chrome.exe -> chromium-1234 dir
    p = Path(exe)
    for parent in p.parents:
        if re.match(r"chromium-\d+$", parent.name):
            return parent
    raise RuntimeError(f"Could not locate chromium-<ver> folder from {exe}")


EXCLUDES = [
    # OpenCV — server-side only (src/compare.py). The agent produces images;
    # the aspect-ratio comparison/shape analysis runs on the server. Its large
    # .pyd is also what broke PyInstaller one-file extraction.
    "cv2",
    # Server-only web stack — never used by the agent.
    "fastapi", "uvicorn", "starlette", "httpx", "httpcore", "h11",
    # phash is now numpy-only; these are no longer needed and are large.
    "scipy", "imagehash",
    # Common accidental heavyweight sweeps.
    "matplotlib", "PyQt5", "PyQt6", "PySide2", "PySide6",
    "pandas", "notebook", "IPython", "tkinter.test", "test",
]

_SPEC_TEMPLATE = '''# Auto-generated by build_agent.py — do not edit by hand.
# Bundles ONLY the resolved Chromium folder (no Firefox/WebKit/headless_shell)
# and excludes server-only + unused heavy modules. The browser tree is added
# via Analysis(datas=...) with a recursive Tree so chrome.exe and every nested
# binary are preserved (a plain --add-data drops chrome.exe).
import os
from PyInstaller.utils.hooks import collect_all

CHROME_DIR = r"{chrome_dir}"
CHROME_PREFIX = "ms-playwright/{chrome_name}"

# Playwright package data/binaries/hidden imports (2-tuples for datas param).
pw_datas, pw_binaries, pw_hidden = collect_all("playwright")

# --- Runtime dependencies the BOOTSTRAP does not statically import -----------
# The entry point is agent_bootstrap.py, which loads agent_gui/agent/src/config
# at runtime from the writable code/ folder. Because that import is dynamic,
# PyInstaller's static scan cannot see the third-party packages the real code
# needs — so their DATA FILES and BINARIES (not just the .py modules) would be
# left out. That is exactly what broke Tcl/Tk: tkinter's tcl8.6/tk8.6 data was
# never collected once agent_gui stopped being the entry script.
#
# collect_all() returns (datas, binaries, hiddenimports) for a package, which
# for tkinter includes the Tcl/Tk runtime the bootloader looks for, for PIL its
# codecs, for numpy its DLLs, etc. Collect every runtime dep this way so a
# clean extract has everything, regardless of what the bootstrap imports.
_extra_datas, _extra_binaries, _extra_hidden = [], [], []
for _pkg in ("tkinter", "PIL", "pystray", "numpy", "requests",
             "dotenv", "certifi", "charset_normalizer"):
    try:
        _d, _b, _h = collect_all(_pkg)
        _extra_datas += _d
        _extra_binaries += _b
        _extra_hidden += _h
    except Exception as _exc:
        print(f"[spec] collect_all({{_pkg!r}}) skipped: {{_exc}}")

# _tkinter is the C extension behind tkinter; name it explicitly so the hook
# that bundles the Tcl/Tk data trees is triggered even though nothing in the
# static graph imports tkinter.
_extra_hidden += ["tkinter", "_tkinter"]

# Recursively enumerate the Chromium folder as (source, dest_dir) 2-tuples so
# the Analysis normaliser turns them into proper 3-tuple DATA entries.
chrome_datas = []
for _r, _d, _files in os.walk(CHROME_DIR):
    for _f in _files:
        _src = os.path.join(_r, _f)
        _reldir = os.path.relpath(_r, CHROME_DIR)
        _dest = CHROME_PREFIX if _reldir == "." else os.path.join(CHROME_PREFIX, _reldir)
        chrome_datas.append((_src, _dest))

# The updatable code ships as a READ-ONLY baseline under _internal/code_baseline.
# On first launch agent_bootstrap.py copies it to a WRITABLE <app>/code folder
# and puts that folder first on sys.path, so self-update only has to replace the
# ~1 MB of Python there — never the Chromium runtime. agent.py / agent_gui.py /
# src / config are therefore NOT frozen into the PYZ; they load from code/.
code_baseline = []
for _name in ("agent.py", "agent_gui.py"):
    code_baseline.append((_name, "code_baseline"))
for _folder in ("src", "config"):
    for _r, _d, _files in os.walk(_folder):
        if "__pycache__" in _r:
            continue
        for _f in _files:
            if _f.endswith((".pyc", ".pyo")):
                continue
            _src = os.path.join(_r, _f)
            _dest = os.path.join("code_baseline", _r)
            code_baseline.append((_src, _dest))
# Record the baseline code version so a fresh install knows where it started.
code_baseline.append(("code_version.txt", "code_baseline"))

a = Analysis(
    ["agent_bootstrap.py"],
    pathex=[r"{root}"],
    binaries=pw_binaries + _extra_binaries,
    datas=code_baseline + pw_datas + chrome_datas + _extra_datas,
    # The bootstrap imports agent_gui dynamically from code/, so PyInstaller's
    # static scan won't discover the agent's third-party deps. collect_all above
    # gathers each package's data + binaries + submodules; add the few explicit
    # submodule names that collect_all does not always pull in.
    hiddenimports=[
        "pystray._win32", "PIL.Image", "PIL.ImageDraw",
        "playwright.sync_api",
    ] + pw_hidden + _extra_hidden,
    hookspath=[],
    runtime_hooks=["pyi_rth_playwright.py"],
    excludes={excludes},
    noarchive=False,
)
pyz = PYZ(a.pure)
# ONE-DIR build: the bootloader loads files from the app folder directly, so
# there is NO runtime extraction step — this avoids the "decompression return
# code -1" failure that one-file hits on large files (chrome.dll, cv2.pyd).
exe = EXE(
    pyz, a.scripts, [],
    exclude_binaries=True,
    name="ArtworkAgent",
    debug=False, bootloader_ignore_signals=False, strip=False,
    upx=False, console={console}, disable_windowed_traceback=False,
)
coll = COLLECT(
    exe, a.binaries, a.datas,
    strip=False, upx=False, name="ArtworkAgent",
)
'''


def main() -> None:
    root = Path(__file__).parent
    chrome_dir = chromium_folder()
    print(f"[build] bundling only: {chrome_dir.name}  ({chrome_dir})")

    # Stamp the code baseline with the current AGENT_CODE_VERSION so a fresh
    # install starts from a known version and the self-updater can compare.
    try:
        from config.agent_version import AGENT_CODE_VERSION
    except Exception:
        AGENT_CODE_VERSION = "0.0.0"
    (root / "code_version.txt").write_text(AGENT_CODE_VERSION, encoding="utf-8")
    print(f"[build] code baseline version: {AGENT_CODE_VERSION}")

    spec_path = root / "ArtworkAgent.spec"
    console = os.getenv("AGENT_BUILD_CONSOLE") == "1"
    spec_path.write_text(_SPEC_TEMPLATE.format(
        chrome_dir=str(chrome_dir), chrome_name=chrome_dir.name,
        root=str(root), excludes=repr(EXCLUDES), console=str(console),
    ), encoding="utf-8")

    print("[build] running PyInstaller from generated spec…")
    subprocess.check_call(
        [sys.executable, "-m", "PyInstaller", "--noconfirm", "--clean", str(spec_path)],
        cwd=str(root),
    )

    app_dir = root / "dist" / "ArtworkAgent"
    exe = app_dir / "ArtworkAgent.exe"
    if not exe.exists():
        print("[build] FAILED — dist/ArtworkAgent/ArtworkAgent.exe not found.")
        sys.exit(1)

    # Folder size (what the designer unzips to).
    folder_bytes = sum(f.stat().st_size for f in app_dir.rglob("*") if f.is_file())

    # Zip the one-dir app for distribution.
    import shutil
    zip_base = root / "dist" / "ArtworkAgent"
    print("[build] zipping the app folder for distribution…")
    zip_path = Path(shutil.make_archive(str(zip_base), "zip", root_dir=str(root / "dist"), base_dir="ArtworkAgent"))
    zip_bytes = zip_path.stat().st_size

    print()
    print(f"[build] DONE (one-dir): {app_dir}")
    print(f"[build] unpacked folder: {folder_bytes:,} bytes  (~{folder_bytes/(1024*1024):.0f} MB)")
    print(f"[build] download ZIP:    {zip_path}")
    print(f"[build] zip size:        {zip_bytes:,} bytes  (~{zip_bytes/(1024*1024):.0f} MB)")
    print("[build] copy dist/ArtworkAgent.zip into the server's downloads/ folder to publish it.")
    print("[build] NOTE: this full ZIP is for FIRST INSTALL only. After that,")
    print("[build]       designers self-update code via /api/agent/code-bundle —")
    print("[build]       just bump AGENT_CODE_VERSION in config/agent_version.py.")


if __name__ == "__main__":
    main()
