"""Saving a generated file back into PrintShop's vault.

The shop's file name IS the design's identity: AW-<CLIENT>-<NNNN>-WRK<VV>. That
name carries a running version number, it has to land in whichever spelling of
the "Artworks" folder that customer already uses, and the new row has to inherit
the design's lead, customer, order, agent and designer. PrintShop already does
all of that in one place. Re-deriving any of it here would eventually produce a
name that disagrees with PrintShop's — and in this shop two files disagreeing
about a name is two files claiming to be the same design.

So this module does not name, file or index anything. It hands the bytes to
PrintShop's own save endpoint and lets the one namer decide, exactly as the
Design Studio's editor and mockup tools do.

Auth is the same short-lived HS256 token those tools use. We mint it here rather
than carry one in from a link, so nothing sensitive ever travels in a URL on
this app's plain-HTTP address.
"""

from __future__ import annotations

import base64
import hashlib
import hmac
import json
import os
import time

import requests

# PrintShop's backend. Reached over the docker bridge, not the public interface,
# so the token never leaves this host.
BACKEND = os.getenv("PRINTSHOP_BACKEND", "http://172.17.0.1:8094").rstrip("/")

# These three must match backend/src/modules/artworks/artwork-studio.service.js
# exactly — PrintShop rejects the token otherwise.
_AUDIENCE = "decoinks-design-studio"
_ISSUER = "decoinks-printshop"
_PURPOSE = "design-studio-artwork"
_TTL_SECONDS = 7200


class PrintshopError(RuntimeError):
    """PrintShop refused the save, with its own message."""

    def __init__(self, message: str, status: int = 502):
        super().__init__(message)
        self.status = status


def _secret() -> str:
    secret = os.getenv("PRINTSHOP_JWT_SECRET") or os.getenv("JWT_SECRET") or ""
    if not secret:
        raise PrintshopError(
            "PRINTSHOP_JWT_SECRET is not set — this app cannot save into the "
            "PrintShop vault until it is.", 500)
    return secret


def _b64(raw: bytes) -> bytes:
    # JWT uses base64url with the padding stripped.
    return base64.urlsafe_b64encode(raw).rstrip(b"=")


def artwork_token(asset_id: str) -> str:
    """A short-lived token scoped to one vault asset.

    Assembled by hand rather than with PyJWT: this is the whole of HS256 —
    sign "<header>.<payload>" with the shared secret — and it keeps a
    Playwright-sized image from growing a dependency for twelve lines.
    """
    if not str(asset_id or "").strip():
        raise PrintshopError("No artwork was handed over to save against.", 400)
    now = int(time.time())
    header = {"alg": "HS256", "typ": "JWT"}
    payload = {
        "purpose": _PURPOSE,
        "asset_id": str(asset_id),
        "user_id": None,
        "iat": now,
        "exp": now + _TTL_SECONDS,
        "aud": _AUDIENCE,
        "iss": _ISSUER,
    }
    signing_input = b".".join(
        _b64(json.dumps(part, separators=(",", ":"), sort_keys=True).encode())
        for part in (header, payload)
    )
    signature = hmac.new(_secret().encode(), signing_input, hashlib.sha256).digest()
    return (signing_input + b"." + _b64(signature)).decode()


def save_working_file(asset_id: str, file_name: str, data: bytes, mime: str) -> dict:
    """Send the generated bytes to PrintShop as the design's next WRK version.

    PrintShop picks the name, the folder and the version, then indexes the new
    file — so it appears in the Design Studio vault without a sync.
    """
    if not data:
        raise PrintshopError("The generated file is empty.", 400)
    try:
        response = requests.post(
            f"{BACKEND}/api/artworks/studio/save",
            data={"token": artwork_token(asset_id), "kind": "WRK"},
            files={"file": (file_name or "artwork.png", data, mime or "image/png")},
            timeout=120,
        )
    except requests.RequestException as exc:
        raise PrintshopError(f"PrintShop could not be reached: {exc}") from exc

    try:
        body = response.json()
    except ValueError:
        body = {}
    if not response.ok:
        # PrintShop's own wording is more useful than anything we could invent.
        raise PrintshopError(
            body.get("message") or body.get("detail")
            or f"PrintShop refused the save ({response.status_code}).",
            response.status_code)

    saved = body.get("data") or {}
    return {
        "name": saved.get("file_name") or "",
        "path": saved.get("path") or "",
        "version_no": saved.get("version_no"),
        "stage": saved.get("lifecycle_code") or "WRK",
    }
